services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: codigo
    ports:
      - 5440:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 8060:80
